-- LinkPulse migration 002: richer click attribution
ALTER TABLE clicks ADD COLUMN IF NOT EXISTS app_source TEXT NOT NULL DEFAULT '';
ALTER TABLE clicks ADD COLUMN IF NOT EXISTS browser    TEXT NOT NULL DEFAULT '';
ALTER TABLE clicks ADD COLUMN IF NOT EXISTS os         TEXT NOT NULL DEFAULT '';
ALTER TABLE clicks ADD COLUMN IF NOT EXISTS lang       TEXT NOT NULL DEFAULT '';
ALTER TABLE clicks ADD COLUMN IF NOT EXISTS is_repeat  BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE clicks ADD COLUMN IF NOT EXISTS utm_source TEXT NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_clicks_repeat ON clicks (link_id, ip_hash, ts DESC);
