-- LinkPulse migration 003: A/B testing
ALTER TABLE links ADD COLUMN IF NOT EXISTS target_b TEXT NOT NULL DEFAULT '';
ALTER TABLE links ADD COLUMN IF NOT EXISTS ab_split INT NOT NULL DEFAULT 50;
ALTER TABLE clicks ADD COLUMN IF NOT EXISTS variant TEXT NOT NULL DEFAULT '';
